# Generated by Django 5.2.17 on 2026-08-31 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Only letters are allowed. Minimum 3 and maximum 40 characters.', regex='^[A-Za-z]{3,40}$')])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Only letters are allowed. Minimum 3 and maximum 40 characters.', regex='^[A-Za-z]{3,40}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9][0-9]{9}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Enter a valid email such as name@gmail.com, name@email.com, or name@yahoo.com.', regex='^[A-Za-z0-9._%+-]+@(gmail|email|yahoo)\\.(com|in)$')])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
