# Generated by Django 5.2.17 on 2026-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'Ab Negative')], max_length=3),
        ),
    ]
