# Generated by Django 5.2.17 on 2026-08-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('doctor_name', models.CharField(default='Dr. Robert Smith', max_length=100)),
                ('diagnosis', models.CharField(max_length=255)),
                ('blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('pulse', models.CharField(default='76', max_length=10)),
                ('temperature', models.CharField(default='98.6', max_length=10)),
                ('medicines', models.TextField(help_text='Prescribed medicine lines with dosage instructions')),
                ('lab_tests', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_recipes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
    ]
