# Generated by Django 5.2.17 on 2026-09-05 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('prescriptions', '0002_remove_prescription_lab_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='consultations.consultation'),
        ),
    ]
