# Generated by Django 5.2.17 on 2026-09-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
    ]
