# Generated by Django 5.2.17 on 2026-08-31 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=20, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('category', models.CharField(default='General Pathology', max_length=100)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('SERUM', 'Serum'), ('URINE', 'Urine'), ('SWAB', 'Swab'), ('OTHER', 'Other')], default='BLOOD', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('normal_range', models.CharField(default='Normal', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('turnaround_time', models.CharField(default='2-4 Hours', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('sample_type', models.CharField(default='Blood', max_length=50)),
                ('ordered_by_doctor', models.CharField(default='Dr. Robert Smith', max_length=100)),
                ('technician_name', models.CharField(default='Mark Vance', max_length=100)),
                ('status', models.CharField(choices=[('PENDING_SAMPLE', 'Pending Sample'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Completed')], default='PENDING_SAMPLE', max_length=20)),
                ('result_value', models.CharField(blank=True, default='', max_length=100)),
                ('reference_range', models.CharField(blank=True, default='', max_length=100)),
                ('finding_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
            ],
        ),
    ]
