# Generated by Django 5.2.17 on 2026-09-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0002_alter_patient_patient_id'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='technician_name',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='test_name',
        ),
        migrations.AddField(
            model_name='labreport',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_lab_reports', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='laboratory.labtest'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='ordered_by_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_lab_reports', to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_reports', to='patients.patient'),
        ),
    ]
