# Generated by Django 5.2.17 on 2026-09-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=15, help_text='Appointment slot duration in minutes.')),
                ('doctor', models.ForeignKey(limit_choices_to={'user__role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['doctor', 'day_of_week', 'available_from'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day_of_week', 'available_from', 'available_to'), name='unique_doctor_availability')],
            },
        ),
    ]
