# Generated by Django 5.2.17 on 2026-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('dosage_form', models.CharField(blank=True, help_text='e.g. 500mg, 10ml, 250mg/5ml', max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('reorder_level', models.PositiveIntegerField(default=20, help_text='Stock level below which alert is triggered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit in INR', max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost per unit in INR', max_digits=10, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
