# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="supplier",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
