# Generated by Django 5.2.17 on 2026-09-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_supplier'),
        ('pharmacy', '0002_remove_medicine_batch_number_and_more'),
    ]

    operations = [
    ]
