# Generated by Django 5.2.17 on 2026-09-05 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_merge_20260903_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybill',
            name='prescription_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacybillitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='pharmacy.medicinestock'),
        ),
        migrations.AlterField(
            model_name='pharmacybill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
